### ISSUE TITLE
Invalid OIDs used for identifiers

### ISSUE THREAD

**Issue by ohr** [usnistgov/asbestos#126]
The tool generates invalid OIDs in ITI-65 bundles, e.g.

```
masterIdentifier :
  system : urn:ietf:rfc:3986
  value : 1.2.51.83.86.150.2020.11.03.11.44.53.129.1
```

OIDs must not contain multi-digit arcs starting with a 0 (zero). A valid regex for OIDs is e.g. ^([0-2])((\.0)|(\.[1-9][0-9]*))*$

_The integer-valued Unicode label shall contain no characters other than those in the range from the DIGIT
ZERO character to the DIGIT NINE character and shall not commence with a DIGIT ZERO character, unless it has
only a single character and the primary integer value of the arc is zero._ 

(Reference: X.660 : Information technology - Procedures for the operation of object identifier registration authorities, https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-X.660-201107-I!!PDF-E&type=items, Section 7.3)

**Comment by lennart-bos** [comment]
For the "urn:ietf:rfc:3986" system, shouldn't the value start with "urn:oid:" as well?

**Comment by lennart-bos** [comment]
It even says here in the FHIR specs https://www.hl7.org/fhir/identifier-registry.html: 
> For OIDs and UUIDs, use the URN form (urn:oid:  (note: lowercase) and urn:uuid:)

**Comment by ohr** [comment]
Absolutely right.
