### ISSUE TITLE
Need of MHD simulators supporting TLS

### ISSUE THREAD

**Issue by NBailliet** [usnistgov/asbestos#190]
Required by the Swiss specifications on the MHD profile, all transactions part of this profile need to be secured by TLS which means simulators embedded would need to support this.

**Comment by skbhaskarla** [comment]
Swiss specifications do not use OAuth at the moment, correct?

**Comment by oliveregger** [comment]
@skbhaskarla @NBailliet thanks for the feedback
- for the mhealth profile in switzerland there will be no client side certificates necessary (TLS yes, but not client side TLS), we uses  IUA with OAuth see http://fhir.ch/ig/ch-epr-mhealth/iti-iua.html
- nicolas said that he managed that a tls connection can be established
i think this issue can be closed or do I miss something?

**Comment by skbhaskarla** [comment]
OAuth and other extended requirements will be considered in a future release. Closing this issue for now.
