### ISSUE TITLE
NA 2020 Connectathon  FHIR Toolkit 1.1.1 Proxy POST parameters problem

### ISSUE THREAD

**Issue by skbhaskarla** [usnistgov/asbestos#65]
If parameters such as _pretty were used in the POST against the proxy such as:

POST /asbestos/proxy/default__HYLAND?_pretty=true&_format=json

Proxy adds an extra slash to the target base URL before it can pass-on those parameters.  

POST http://hyland26:17025/fhir/MHD/Bundle/?_pretty=true&_format=json
This is the cause of the POST problem in the Reference Example (see below). This will have to be fixed in the FHIR Toolkit.

CAT IHE USA NA 2020  Reference Example: http://nist1:9760/session/default/channel/HYLAND/lognav/2020_01_23_09_55_21_813

**Comment by iheos** [comment]
Fixed.  Covered by ChannelConfigTest.withPretty()
