### ISSUE TITLE
Bundle.entry.request.url - can it be symbolic name?

### ISSUE THREAD

**Issue by iheos** [usnistgov/asbestos#89]
If not label with error

**Comment by skbhaskarla** [comment]
https://hl7.org/fhir/bundle-definitions.html#Bundle.entry.request.url
Comments from the link above seems to suggest the resource name to be used in a pure REST style FHIR service.
With MHD bundle transactions, all resource entries in the PDB bundle are translated to non-REST like XDS metadata/repository objects so it only appears as if the resource is being "created" on the MHD channel proxy. In this case, symbolic name or the using the temporary Bundle.entry.fullUrl seems to make sense.
