### ISSUE TITLE
<reference value="#962a0698-466c-4487-852b-1fd2f90c788b" />

### ISSUE THREAD

**Issue by iheos** [usnistgov/asbestos#90]
valid format?

**Comment by skbhaskarla** [comment]
According to https://hl7.org/fhir/R4/references.html#contained, 
Both Reference and canonical types may refer to contained resources.
Also, see "An example of a contained resource."

In this case, the reference in question seems to represent a contained resource, so it is valid format.

The base resource id element is a string type with a limit up to 64 characters.
