### ISSUE TITLE
validations to add to PDB Validations

### ISSUE THREAD

**Issue by iheos** [usnistgov/asbestos#99]
1. Binary.contentType must equals DocumentReference.content.attachment.contentType
2. fullURL should not be in PDB-request
3. In PDB-response - fullURL must agree with id and resource type and content of meta.url

**Comment by iheos** [comment]
Validation 1 seems impossible to write in FHIRPATH.  I have

Bundle.entry.select((resource as DocumentReference).content.attachment).all($this.contentType = Bundle.entry.fullUrl)

which is insufficient.  At the end, Bundle.entry.fullUrl needs a where clause to match against attachment.url.  This would reset $this.  But following the match, I need to again refere to $this.contentType.  With the approach I've taken there is not a way to keep this state for matching. For now I cannot find a better approach.

**Comment by iheos** [comment]
2 and 3 moved to separate issues.

**Comment by skbhaskarla** [comment]
https://github.com/usnistgov/asbestos/blob/171670bfd11e986cbb5c93f36fc917c392d59838/asbestos-war/src/main/webapp/data/TestCollections/Library/DocumentReferenceRequirements.xml#L62
